import type { Metadata } from "next";
import { Open_Sans, Playfair_Display, Julee } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Provider from "@/utils/Provider";
import MotionDiv from "@/components/MotionDiv";

const openSans = Open_Sans({ subsets: ["latin"], variable:'--font-open-sans' });
const playfair = Playfair_Display({subsets: ["latin"], variable: '--font-playfair', weight: '400'})
const julee = Julee({subsets: ["latin"], variable: '--font-julee', weight:'400'})

const variants = {
  hidden: { opacity:0, x:-200, y:0 },
  enter: {opacity:1, x:0, y:0}
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${openSans.variable} ${playfair.variable} ${julee.variable} bg-grey dark:bg-dark-color text-dark-color dark:text-grey`}>
        <Provider>
          <div>
            <Navbar/>
            <MotionDiv variants={variants} initial="hidden" animate="enter" transition={{type: 'linear'}} className="overflow-hidden">
            {children}
            </MotionDiv>
            <Footer/>
          </div>
        </Provider>
      </body>
    </html>
  );
}
